### ISSUE TITLE
Xcode 9.3 compile error

### ISSUE THREAD

**Issue by EricMentele** [bluesnap/bluesnap-ios#1]
After updating to Xcode 9.3 I see this compile error in the Blue Snap SDK code:

<img width="902" alt="screen shot 2018-04-26 at 9 58 13 pm" src="https://user-images.githubusercontent.com/5101005/39345399-14709a56-499d-11e8-8005-913a1dc78dd3.png">

Is there a recommended solution or update?

**Comment by snpori** [comment]
This is fixed in the most recent version.
I guess you have discovered this by now and that's why you have decided to close it.

**Comment by EricMentele** [comment]
Indeed :). Thank you.
