### ISSUE TITLE
Swift 4.2 / Xcode 10 update?

### ISSUE THREAD

**Issue by teo029** [bluesnap/bluesnap-ios#4]
Project needs to be updated to Swift 4.2 / Xcode 10.

**Comment by mp3il** [comment]
any news about this? how should we use this sdk with swift 4.2?

**Comment by teo029** [comment]
> any news about this? how should we use this sdk with swift 4.2?

Check my fork.

**Comment by mp3il** [comment]
@teo029 thanks, any idea what can cause the error:


Showing All Messages
:-1: duplicate output file '/Users/user/Library/Developer/Xcode/DerivedData/TshirtWars-eqpvanznewocjmcrojamlgcqoptc/Build/Products/Debug-iphonesimulator/BluesnapSDK/BluesnapSDK.framework/Headers/KDataCollector.h' on task: CpHeader /Users/user/Documents/Apps/TShirtWars/iOS/TshirtWars/Pods/BluesnapSDK/BluesnapSDK/Kount/KDataCollector.h /Users/user/Library/Developer/Xcode/DerivedData/TshirtWars-eqpvanznewocjmcrojamlgcqoptc/Build/Products/Debug-iphonesimulator/BluesnapSDK/BluesnapSDK.framework/Headers/KDataCollector.h (in target 'BluesnapSDK')

**Comment by teo029** [comment]
Somewhat. I could've have resolved that, but was not sure what the cause was.

A workaround for me was removing the `KDataCollector.h files` and `libKountDataCollector.h` from the Bluesnap target. (or some combination like this). In short, remove one / both of those files from target until it works.

**Comment by mp3il** [comment]
Oh god, you're right, they were duplicated, I had to remove reference for the duplicated instance from the target.

thank you so much.

**Comment by snpori** [comment]
Project was updated to swift 4.2
Let's hope the swift ABI issue is solved by Apple soon...
