### ISSUE TITLE
Compile error after update to Xcode 10.2

### ISSUE THREAD

**Issue by odvan** [bluesnap/bluesnap-ios#9]
Compile error after update to Xcode 10.2.

**Comment by markokoleznik** [comment]
Same here. Have you found any temporary workaround or even better, a solution?

**Comment by snpori** [comment]
Hello. This is currently in progress. we will update to swift5 in the next release.

**Comment by wisron** [comment]
@snpori Any eta on this? it prevents us from upgrading to Xcode 10.2

**Comment by wisron** [comment]
Opened a PR: https://github.com/bluesnap/bluesnap-ios/pull/10

**Comment by azeemse** [comment]
> Hello. This is currently in progress. we will update to swift5 in the next release.

is this issue fixed? can we take the latest pull?

**Comment by snpori** [comment]
The compiler issue is resolved. swift5 is still in progress.
